### ISSUE TITLE
Support reading whole CSV files (as strings)

### ISSUE THREAD

**Issue by qiemem** [qiemem/CSV-Extension#3]
One motivation here is that CSV can have newlines in items as long as the items are quoted. The extension supports this just fine for a single row. However, since the majority of the time people are going to be reading line by line from CSV file, this doesn't really help. People would have to implement there own parsing scheme to detect when a newlines separates rows vs is just part of an item.

**Comment by SethTisue** [comment]
should this issue be transferred to NetLogo/CSV-Extension?

**Comment by qiemem** [comment]
This feature is already included in NetLogo/CSV-Extension! `csv:from-file`

**Comment by SethTisue** [comment]
so close the issue?
